Fix testcode
kikikiki2727/rspec_app_exam pull request #1
Opened 2021-04-25 10:52 UTC by kikikiki2727

RSpec編、04_テストコード修正

【FIXMEについて】
・'Project詳細からTask一覧ページにアクセスした場合、Taskが表示されること'
'View Todos'を押すと別タブが開かれるので、「switch_to_window(windows.last)」を追加。

・'Taskを編集した場合、一覧画面で編集後の内容が表示されること'
表示時刻の部分をビューで使用しているメソッドを使って修正。

・'Taskが削除されること'
「expect(page)・・・」部分がビュー内の他の文言と重複してしまうので、対象範囲を'task_list'だけに修正。

【TODOについて】
・letとlet!を用いて、ローカル変数の部分を修正。
・「let(:task)」について、taskのファクトリで「association :project」と記載して紐づけると、テスト内でletで定義しているprojectと違うprojectと紐づいてしまうので、明示的に「project_id: project.id」と記載して、「let(:project)」のprojectと「let(:task)」を紐づけた。

【ファクトリについて】
・トレイトを使って、すでにステータスが完了したタスクを追加。

【rails_helper】
・ビュー側で使用されている表示時刻のメソッドを使用するためにヘルパーを読み込むように修正。

2021-04-26 07:56 UTC, yuji91 requested changes
修正内容はほとんど問題ありませんでしたが、気になった点をコメントしました！

2021-04-26 07:56 UTC, yuji91 commented on spec/factories/tasks.rb
> +      project_id { 1 }
親のIDを直で指定するのは良くないですね。
仮に途中で削除、作成処理が入ることでIDがずれるとテストが破綻してしまいます。

コメントアウトされている`association`を活用するようにしましょう!

2021-04-26 07:56 UTC, yuji91 commented on spec/system/task_spec.rb
> +  let(:task) { create(:task, project_id: project.id) }
associationを活用してこの記載を省いてみましょう！
```suggestion
  let(:task) { create(:task) }
```

2021-04-26 10:55 UTC, kikikiki2727 commented on spec/factories/tasks.rb
> +      project_id { 1 }
レビューありがとうございます！

1つ質問なのですが、「project_id { 1 }」と明示的に指定して紐付けないと、下記画像のようにproject_idが2のprojectと紐づいてしまうのですが、問題ないのでしょうか？？

「visit edit_project_task_path(project, completion_task)」
ここの部分をデバッグしたところ、変数「project」はIDが'1'で、変数「completion_task」のproject_idは'2'になっていて、IDがずれてしまっているので疑問に思いました。

これだとURLは「projects/1/tasks/1/edit」という風になると思うのですが、変数「completion_task」はprojectのIDが'2'のprojectと紐づけられているので、「projects/2/tasks/1/edit」というURLじゃないと、変数「completion_task」の編集ページに行けないと思うのですが、私は何か誤認してしまっているのでしょうか？？

よろしくお願いいたします。

<img width="583" alt="RSpec質問" src="https://user-images.githubusercontent.com/77670285/116065223-c2adc880-a6c1-11eb-999c-2fd84785f8e7.png">


【現時点で私が想定している挙動】
「visit edit_project_task_path(project, completion_task)」の部分の"project"と「association :project」で関連づけられる"project"は別のproject

前者はprojectのIDが'1'で、後者のprojectのIDは'2'になる。

`RSpec.describe 'Task', type: :system do
    let(:project) { create(:project) }
    let(:task) { create(:task) }
    let(:completion_task) { create(:task, :completion_task) }
`

`FactoryBot.define do
  factory :task do
    title { 'Task' }
    status { rand(2) }
    from = Date.parse("2019/08/01")
    to   = Date.parse("2019/12/31")
    deadline { Random.rand(from..to) }
    association :project

    trait :completion_task do
      status { :done } 
      completion_date { Time.current.yesterday }
    end
  end
end`

`    fit '既にステータスが完了のタスクのステータスを変更した場合、Taskの完了日が更新されないこと' do
        # TODO: FactoryBotのtraitを利用してください
        visit edit_project_task_path(project, completion_task)
        select 'todo', from: 'Status'
        click_button 'Update Task'
        expect(page).to have_content('todo')
        expect(page).not_to have_content(Time.current.strftime('%Y-%m-%d'))
        byebug
        expect(current_path).to eq project_task_path(project, completion_task)
     end`

2021-04-26 11:52 UTC, yuji91 commented on spec/factories/tasks.rb
> +      project_id { 1 }
`visit edit_project_task_path(completion_task.project, completion_task)`でどうでしょうか？

2021-04-26 12:45 UTC, kikikiki2727 commented on spec/factories/tasks.rb
> +      project_id { 1 }
「visit edit_project_task_path(completion_task.project, completion_task)」でデバッグしたところIDがずれなくなりました！

そこでまた新たな疑問が生まれたのですが、
他のテストの部分でtaskとprojectを呼び出す時も「task.project」と「task」の方がいいのではないかと思いました。

例えば下記のテストの部分とかです。

```ruby
describe 'Task詳細' do
    context '正常系' do
      it 'Taskが表示されること' do
        # TODO: ローカル変数ではなく let を使用してください
        visit project_task_path(project, task)
        expect(page).to have_content(task.title)
        byebug
        expect(page).to have_content(task.status)
        expect(page).to have_content(task.deadline.strftime('%Y-%m-%d %H:%M'))
        expect(current_path).to eq project_task_path(project, task)
      end
    end
  end
```

上記のように記載していたのですが、こちらもデバッグしてみたところ、先程質問したところと同じようにprojectのIDがずれていました。

そしてこちらも
「visit project_task_path(task.project, task)」に変えてみたところ、IDのずれはなくなりました。

ただもう一つ疑問なのは、最初に質問したテストもそうなのですが、projectのIDがずれていてもテストに通ってしまうことです。

だとしたらprojectのIDとtaskのproject_idは、ずれていても問題ないということなのでしょうか？？

よろしくお願いいたします。

2021-04-26 14:50 UTC, kikikiki2727 commented on spec/factories/tasks.rb
> +      project_id { 1 }
ここの部分でございます。
1枚目：byebugで変数を確認。変数projectのIDが1で、変数taskのproject_idが2の状態。
2枚目：byebugをコメントアウトしてテストを実行。パスする。

<img width="594" alt=" RSpec質問2" src="https://user-images.githubusercontent.com/77670285/116101437-c6087a80-a6e8-11eb-9d13-3e0b2ceafd67.png">
<img width="584" alt="RSpec質問3" src="https://user-images.githubusercontent.com/77670285/116101468-cc96f200-a6e8-11eb-9014-dafd68f76e65.png">

spec/factories/tasks.rb
```ruby
FactoryBot.define do
  factory :task do
    title { 'Task' }
    status { rand(2) }
    from = Date.parse("2019/08/01")
    to   = Date.parse("2019/12/31")
    deadline { Random.rand(from..to) }
    association :project

    trait :completion_task do
      status { :done } 
      completion_date { Time.current.yesterday }
    end
  end
end
```

※下記のコードの一部分だけ、一旦IDがずれていたときに戻しています。コミットはしていません。

spec/system/task_spec.rb
```ruby
RSpec.describe 'Task', type: :system do
  let(:project) { create(:project) }
  let(:task) { create(:task) }
  let(:completion_task) { create(:task, :completion_task) }


describe 'Task詳細' do
    context '正常系' do
      fit 'Taskが表示されること' do
        # TODO: ローカル変数ではなく let を使用してください
        visit project_task_path(project, task)　　　# ← 「visit project_task_path(task.project, task)」
        expect(page).to have_content(task.title)
        # byebug
        expect(page).to have_content(task.status)
        expect(page).to have_content(task.deadline.strftime('%Y-%m-%d %H:%M'))
        expect(current_path).to eq project_task_path(project, task)　　# ←「expect(current_path).to eq project_task_path(task.project, task)」
      end
    end
  end
```

2021-04-26 15:04 UTC, kikikiki2727 commented on spec/factories/tasks.rb
> +      project_id { 1 }
こちらはcompletion_taskの方です。

1枚目：byebugで変数を確認。変数projectのIDが1で、変数taskのproject_idが2の状態。
2枚目：byebugをコメントアウトしてテストを実行。パスする。

<img width="591" alt="RSpec質問4" src="https://user-images.githubusercontent.com/77670285/116104940-d40bca80-a6eb-11eb-95a8-d70da40a1cb1.png">
<img width="603" alt="RSpec質問5" src="https://user-images.githubusercontent.com/77670285/116104973-d9691500-a6eb-11eb-8792-b755b7f972d0.png">

spec/system/task_spec.rb
```ruby
      fit '既にステータスが完了のタスクのステータスを変更した場合、Taskの完了日が更新されないこと' do
        # TODO: FactoryBotのtraitを利用してください
        visit edit_project_task_path(project, completion_task)　　# ← 「visit edit_project_task_path(completion_task.project, completion_task)」
        # byebug
        select 'todo', from: 'Status'
        click_button 'Update Task'
        expect(page).to have_content('todo')
        expect(page).not_to have_content(Time.current.strftime('%Y-%m-%d'))
        expect(current_path).to eq project_task_path(project, completion_task)　　# ← 「expect(current_path).to eq project_task_path(completion_task.project, completion_task)」
      end
```

2021-04-28 04:50 UTC, yuji91 commented on spec/factories/tasks.rb
> +      project_id { 1 }
これは実装側に残っていたバグが原因でした。
以下PRで対応したので、申し訳ありませんがこちらのマージをお願いします🙇
https://github.com/kikikiki2727/rspec_app_exam/pull/2

2021-04-28 08:27 UTC, kikikiki2727 commented on spec/factories/tasks.rb
> +      project_id { 1 }
ローカルにpullして確認してみたところ、IDがずれているとしっかりとエラーになりました！
これで課題4は完了でしょうか？？

2021-04-28 09:15 UTC, yuji91 approved these changes

2021-04-28 09:45 UTC, merged